/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javausertable;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author User
 */
public class ViewNews extends javax.swing.JPanel {

    /**
     * Creates new form ViewNews
     */
    JSONObject news;
    public ViewNews(JSONObject news) {
        initComponents();
        this.news = news;
        String content = (String)news.get("content");
        Title.setText((String)news.get("title"));
        String formatted = content.replace("\n", "<br>");
        Content.setText("<html><body style='width: 500px; text-align: justify'>" + formatted + "</body></html>");
        Content.setBackground(new Color(30,40,44));
        CreationDate.setText( (String)news.get("creationDate"));
        Author.setText( (String)news.get("author"));
        String url =  (String)news.get("link");
         OpenLink.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    // Mở URL bằng trình duyệt mặc định
                    Desktop.getDesktop().browse(new URI(url));
                } 
                catch (IOException | URISyntaxException ex) {
                    ex.printStackTrace();
                   
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Author = new javax.swing.JLabel();
        CreationDate = new javax.swing.JLabel();
        OpenLink = new javax.swing.JButton();
        Content = new javax.swing.JLabel();

        setBackground(new java.awt.Color(30, 40, 44));
        setPreferredSize(new java.awt.Dimension(766, 476));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setHorizontalScrollBar(null);

        jPanel2.setBackground(new java.awt.Color(30, 40, 44));
        jPanel2.setLayout(new java.awt.BorderLayout());

        Title.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Title.setForeground(new java.awt.Color(242, 242, 242));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("TITLE");
        jPanel2.add(Title, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(30, 40, 44));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(30, 40, 44));
        jPanel6.setPreferredSize(new java.awt.Dimension(522, 50));

        Author.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Author.setForeground(new java.awt.Color(242, 242, 242));
        Author.setText("jLabel3");
        Author.setPreferredSize(new java.awt.Dimension(100, 15));

        CreationDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CreationDate.setForeground(new java.awt.Color(242, 242, 242));
        CreationDate.setText("jLabel5");

        OpenLink.setBackground(new java.awt.Color(30, 40, 44));
        OpenLink.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        OpenLink.setForeground(new java.awt.Color(255, 255, 255));
        OpenLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javausertable/icon/Link.png"))); // NOI18N
        OpenLink.setText("Original Link");
        OpenLink.setBorder(null);
        OpenLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenLinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(CreationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(OpenLink)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpenLink))
                .addComponent(CreationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        Content.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Content.setForeground(new java.awt.Color(242, 242, 242));
        Content.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Content.setText("jLabel1");
        Content.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(Content, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel2);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void OpenLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenLinkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JLabel Content;
    private javax.swing.JLabel CreationDate;
    private javax.swing.JButton OpenLink;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
